import { GalleryItem, GalleryCategoryMeta } from '@/types/gallery';

export const GALLERY_CATEGORIES: GalleryCategoryMeta[] = [
  {
    id: 'all',
    label: 'সকল ছবি',
    labelEn: 'All Photos',
    description: 'সংগ্রহের সকল ইসলামিক স্থিরচিত্র ও স্থাপত্য',
    iconName: 'LayoutGrid',
  },
  {
    id: 'haramain',
    label: 'পবিত্র হারামাইন',
    labelEn: 'Haramain Sharifain',
    description: 'মক্কা মুকাররমা ও মদিনা মুনাওয়ারার পবিত্র দৃশ্য ও কাবা শরিফ',
    iconName: 'Moon',
  },
  {
    id: 'mosques',
    label: 'ঐতিহাসিক মসজিদ',
    labelEn: 'Historic Mosques',
    description: 'বিশ্বখ্যাত ও ঐতিহ্যবাহী ঐতিহাসিক মসজিদসমূহ',
    iconName: 'Landmark',
  },
  {
    id: 'architecture',
    label: 'ইসলামিক স্থাপত্য',
    labelEn: 'Islamic Architecture',
    description: 'ঐতিহ্যবাহী খিলান, গম্বুজ, জ্যামিতিক কারুকাজ ও মোজাইক নকশা',
    iconName: 'Building2',
  },
  {
    id: 'calligraphy',
    label: 'ক্যালিগ্রাফি ও পাণ্ডুলিপি',
    labelEn: 'Calligraphy & Art',
    description: 'পবিত্র কুরআন ও হাদিসের সুদৃশ্য আরবি ক্যালিগ্রাফি শিল্প',
    iconName: 'PenTool',
  },
  {
    id: 'heritage',
    label: 'ঐতিহ্য ও সংস্কৃতি',
    labelEn: 'Heritage & Life',
    description: 'মুসলিম বিশ্বের প্রাচীন ঐতিহ্য, পাণ্ডুলিপি ও ঐতিহাসিক স্মারক',
    iconName: 'BookOpen',
  },
  {
    id: 'nature',
    label: 'প্রাকৃতিক নিদর্শন',
    labelEn: 'Signs of Nature',
    description: 'আল্লাহর সৃষ্টির অপরূপ সৌন্দর্য, পর্বত, মরুভূমি ও মহাজাগতিক নিদর্শন',
    iconName: 'Sparkles',
  },
];

export const INITIAL_GALLERY_ITEMS: GalleryItem[] = [
  // --- হারামাইন ---
  {
    id: 'photo-1',
    title: 'পবিত্র কাবা শরিফ ও তাওয়াফের দৃশ্য',
    titleEn: 'The Holy Kaaba & Tawaf',
    category: 'haramain',
    categoryLabel: 'পবিত্র হারামাইন',
    imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
    location: 'মক্কা মুকাররমা',
    country: 'সৌদি আরব',
    photographer: 'হায়দার মাহমুদ',
    description: 'রাত্রিকালীন আলোকোজ্জ্বল পবিত্র কাবা শরিফ এবং তাওয়াফরোরত বিশ্ব মুসলিমদের হৃদস্পর্শী দৃশ্য।',
    tags: ['কাবা শরিফ', 'মক্কা', 'তাওয়াফ', 'হজ', 'ওমরাহ', 'হারামাইন'],
    dimensions: '3840 x 2400 (4K UHD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-08-15',
    downloadsCount: 1420,
    likesCount: 890,
  },
  {
    id: 'photo-2',
    title: 'মসজিদুন্নববীর সবুজ গম্বুজ ও মিনার',
    titleEn: 'The Green Dome of Prophet’s Mosque',
    category: 'haramain',
    categoryLabel: 'পবিত্র হারামাইন',
    imageUrl: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&q=80&w=800',
    location: 'মদিনা মুনাওয়ারা',
    country: 'সৌদি আরব',
    photographer: 'আব্দুর রহমান শাকিল',
    description: 'রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের পবিত্র রওজা মোবারক ও মসজিদে নববীর ঐতিহ্যবাহী সবুজ গম্বুজের সোনালী দৃশ্য।',
    tags: ['মদিনা', 'মসজিদে নববী', 'সবুজ গম্বুজ', 'রওজা শরিফ'],
    dimensions: '3200 x 2133 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-08-10',
    downloadsCount: 1890,
    likesCount: 1240,
  },
  {
    id: 'photo-3',
    title: 'মসজিদুন্নববীর স্বয়ংক্রিয় ছাতা ও মার্বেল প্রাঙ্গণ',
    titleEn: 'Umbrellas of Al-Masjid an-Nabawi',
    category: 'haramain',
    categoryLabel: 'পবিত্র হারামাইন',
    imageUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=80&w=800',
    location: 'মদিনা মুনাওয়ারা',
    country: 'সৌদি আরব',
    photographer: 'ফারহান আহমেদ',
    description: 'মসজিদে নববীর বহিরাঙ্গনে ছায়া প্রদানকারী প্রকৌশল ও ইসলামিক শিল্পকলার অনন্য সংমিশ্রণ স্বয়ংক্রিয় বৃহদাকার ছাতা।',
    tags: ['মদিনা', 'মসজিদে নববী', 'স্থাপত্য', 'ছাতা'],
    dimensions: '2800 x 1867 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-08-01',
    downloadsCount: 960,
    likesCount: 650,
  },

  // --- ঐতিহাসিক মসজিদ ---
  {
    id: 'photo-4',
    title: 'বায়তুল মোকাররম জাতীয় মসজিদ',
    titleEn: 'Baitul Mukarram National Mosque',
    category: 'mosques',
    categoryLabel: 'ঐতিহাসিক মসজিদ',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800',
    location: 'ঢাকা',
    country: 'বাংলাদেশ',
    photographer: 'তানভীর হাসান',
    description: 'বাংলাদেশের জাতীয় মসজিদ বায়তুল মোকাররম, যার স্থাপত্যে কাবার নকশার গভীর প্রভাব প্রতিফলিত হয়েছে।',
    tags: ['বায়তুল মোকাররম', 'ঢাকা', 'বাংলাদেশ', 'জাতীয় মসজিদ'],
    dimensions: '3000 x 2000 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-07-28',
    downloadsCount: 750,
    likesCount: 520,
  },
  {
    id: 'photo-5',
    title: 'সুলতান আহমেদ মসজিদ (নীল মসজিদ)',
    titleEn: 'The Blue Mosque (Sultan Ahmed)',
    category: 'mosques',
    categoryLabel: 'ঐতিহাসিক মসজিদ',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800',
    location: 'ইস্তাম্বুল',
    country: 'তুরস্ক',
    photographer: 'কামাল ওজতুর্ক',
    description: 'ওসমানী সাম্রাজ্যের অন্যতম শ্রেষ্ঠ স্থাপত্যকীর্তি ইস্তাম্বুলের নীল মসজিদ ও এর সুরম্য মিনারসমূহ।',
    tags: ['ইস্তাম্বুল', 'তুরস্ক', 'নীল মসজিদ', 'ওসমানী স্থাপত্য'],
    dimensions: '3600 x 2400 (UHD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-07-20',
    downloadsCount: 1120,
    likesCount: 830,
  },
  {
    id: 'photo-6',
    title: 'শেখ জায়েদ গ্র্যান্ড মসজিদ',
    titleEn: 'Sheikh Zayed Grand Mosque',
    category: 'mosques',
    categoryLabel: 'ঐতিহাসিক মসজিদ',
    imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    location: 'আবুধাবি',
    country: 'সংযুক্ত আরব আমিরাত',
    photographer: 'রাশেদ আল-মাররি',
    description: 'শুভ্র মার্বেল পাথর, সোনালী ঝাড়বাতি এবং বিশ্বের বৃহত্তম হাতে বোনা কার্পেট বিশিষ্ট সুরম্য গ্র্যান্ড মসজিদ।',
    tags: ['আবুধাবি', 'শেখ জায়েদ মসজিদ', 'মার্বেল', 'আধুনিক স্থাপত্য'],
    dimensions: '3840 x 2160 (4K UHD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-07-15',
    downloadsCount: 1340,
    likesCount: 970,
  },

  // --- ইসলামিক স্থাপত্য ও নকশা ---
  {
    id: 'photo-7',
    title: 'ঐতিহাসিক ইসলামিক জ্যামিতিক খিলান ও মোজাইক',
    titleEn: 'Islamic Geometric Arches & Mosaic',
    category: 'architecture',
    categoryLabel: 'ইসলামিক স্থাপত্য',
    imageUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&q=80&w=800',
    location: 'কর্ডোবা / আন্দালুসিয়া',
    country: 'স্পেন',
    photographer: 'মারিয়া গনজালেস',
    description: 'মুসলিম আন্দালুসের ঐতিহাসিক স্থাপত্যরীতি, লাল-সাদা ডোরাকাটা অশ্বখুরাকৃতি খিলান ও জ্যামিতিক ভারসাম্য।',
    tags: ['আন্দালুসিয়া', 'কর্ডোবা', 'খিলান', 'জ্যামিতিক শিল্প'],
    dimensions: '2900 x 1933 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-07-08',
    downloadsCount: 880,
    likesCount: 610,
  },
  {
    id: 'photo-8',
    title: 'ঐতিহাসিক মুকারনাস ও কারুকাজ শোভিত সিলিং',
    titleEn: 'Muqarnas Vaulting & Ornamentation',
    category: 'architecture',
    categoryLabel: 'ইসলামিক স্থাপত্য',
    imageUrl: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&q=80&w=800',
    location: 'ইসফাহান',
    country: 'ইরান',
    photographer: 'আমির রেজা',
    description: 'ত্রি-মাত্রিক ঝুলন্ত মুকারনাস কারুকাজ এবং ফিরোজা টাইলসে খচিত গম্বুজের ভিতরাংশের কারুকার্য।',
    tags: ['মুকারনাস', 'টাইলস', 'গম্বুজ', 'ঐতিহাসিক স্থাপত্য'],
    dimensions: '3000 x 2000 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-06-30',
    downloadsCount: 640,
    likesCount: 480,
  },

  // --- ক্যালিগ্রাফি ও পাণ্ডুলিপি ---
  {
    id: 'photo-9',
    title: 'পবিত্র কুরআনুল কারীমের স্বর্ণালী ক্যালিগ্রাফি',
    titleEn: 'Sacred Quranic Calligraphy Manuscript',
    category: 'calligraphy',
    categoryLabel: 'ক্যালিগ্রাফি ও পাণ্ডুলিপি',
    imageUrl: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&q=80&w=800',
    location: 'ইসলামিক মিউজিয়াম',
    country: 'তুরস্ক',
    photographer: 'ওমর কারাসু',
    description: 'হাতে লিখিত প্রাচীন স্বর্ণখচিত পাণ্ডুলিপিতে সুলেস ও নাত লিপির অপরূপ সংমিশ্রণ।',
    tags: ['কুরআন', 'ক্যালিগ্রাফি', 'আরবি লিপি', 'পাণ্ডুলিপি'],
    dimensions: '3400 x 2267 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-06-22',
    downloadsCount: 1560,
    likesCount: 1100,
  },
  {
    id: 'photo-10',
    title: 'হস্তলিখিত ক্লাসিক্যাল আরবি ক্যালিগ্রাফি',
    titleEn: 'Classical Arabic Calligraphy Art',
    category: 'calligraphy',
    categoryLabel: 'ক্যালিগ্রাফি ও পাণ্ডুলিপি',
    imageUrl: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&q=80&w=800',
    location: 'কায়রো',
    country: 'মিশর',
    photographer: 'তাহা আল-মিসরি',
    description: 'ঐতিহ্যবাহী খাগের কলম ও প্রথাগত কালিতে রচিত নূরানী আরবি ক্যালিগ্রাফি।',
    tags: ['ক্যালিগ্রাফি', 'আরবি বর্ণমালা', 'শিল্পকলা', 'খাগের কলম'],
    dimensions: '2800 x 1867 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-06-15',
    downloadsCount: 920,
    likesCount: 710,
  },

  // --- ঐতিহ্য ও সংস্কৃতি ---
  {
    id: 'photo-11',
    title: 'ঐতিহ্যবাহী ইসলামিক পাঠাগার ও গবেষণা সংকলন',
    titleEn: 'Historic Islamic Library & Manuscripts',
    category: 'heritage',
    categoryLabel: 'ঐতিহ্য ও সংস্কৃতি',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800',
    location: 'ফেজ / কায়রাউইন',
    country: 'মরক্কো',
    photographer: 'জায়েদ মনসুর',
    description: 'মুসলিম সোনালী যুগের জ্ঞান-বিজ্ঞান, দর্শন ও তাফসিরের মূল সংগ্রহশালা।',
    tags: ['পাঠাগার', 'পাণ্ডুলিপি', 'জ্ঞানবিজ্ঞান', 'ঐতিহ্য'],
    dimensions: '3200 x 2133 (HD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-06-05',
    downloadsCount: 510,
    likesCount: 390,
  },

  // --- প্রাকৃতিক নিদর্শন ও তাদাব্বুর ---
  {
    id: 'photo-12',
    title: 'জাবাল আল-নূর ও হেরা গুহার ঐতিহাসিক পর্বতমালা',
    titleEn: 'Mount Noor & Peaceful Desert Serenity',
    category: 'nature',
    categoryLabel: 'প্রাকৃতিক নিদর্শন',
    imageUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?auto=format&fit=crop&q=80&w=800',
    location: 'হেজাজ পর্বতমালা',
    country: 'সৌদি আরব',
    photographer: 'সামির আনোয়ার',
    description: 'আল্লাহর অপার সৃষ্টির মাঝে মহিমান্বিত নীরবতা ও সূর্যাস্তের মনোরম চিত্র।',
    tags: ['তাদাব্বুর', 'মরুভূমি', 'সূর্যাস্ত', 'পাহাড়', 'প্রকৃতি'],
    dimensions: '3840 x 2160 (4K UHD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-05-25',
    downloadsCount: 780,
    likesCount: 560,
  },
  {
    id: 'photo-13',
    title: 'মহাজাগতিক নক্ষত্ররাজি ও রাত্রিকালীন সৃষ্টির মহিমা',
    titleEn: 'Starry Cosmic Night & Quranic Reflection',
    category: 'nature',
    categoryLabel: 'প্রাকৃতিক নিদর্শন',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=85&w=2400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
    location: 'মরুভূমি অবজারভেটরি',
    country: 'মিশর',
    photographer: 'হাসান কারিম',
    description: '“তিনিই সৃষ্টি করেছেন নক্ষত্ররাজি, যাতে তোমরা দিকনির্ণয় করতে পার।” (সূরা আনআম: ৯৭)',
    tags: ['নক্ষত্র', 'মহাকাশ', 'তাদাব্বুর', 'আকাশ'],
    dimensions: '3840 x 2160 (4K UHD)',
    aspectRatio: 'landscape',
    uploadedAt: '2026-05-18',
    downloadsCount: 1190,
    likesCount: 880,
  },
];
